title: POML
email: admin@example.com
description: >-
  POML Lab website powered by GitHub Pages and Markdown.
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
collections:
  people:
    output: false
  publications:
    output: false
  news:
    output: false
  gallery:
    output: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
